server.port=${SERVER_PORT:8080}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/qwerty3}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:349349}
#349349
spring.jpa.hibernate.ddl-auto=update

spring.main.allow-circular-references=true